# Generated by Django 3.0.6 on 2020-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.TextField(max_length=30, verbose_name='Matrícula')),
                ('nombre', models.TextField(max_length=200, verbose_name='Nombre')),
                ('carrera', models.TextField(max_length=200, verbose_name='Carrera')),
                ('especialidad', models.TextField(max_length=50, verbose_name='Especialidad')),
                ('cuatrimestre', models.TextField(max_length=20, verbose_name='Cuatrimestre')),
                ('grupo', models.TextField(max_length=5, verbose_name='Grupo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['cuatrimestre', 'grupo', 'especialidad'],
            },
        ),
    ]
