# Generated by Django 3.0.6 on 2020-07-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='especialidad',
            field=models.TextField(max_length=200, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricula',
            field=models.TextField(max_length=15, verbose_name='Matrícula'),
        ),
    ]
